import type { LucideIcon } from "lucide-react";
import {
  Award,
  BarChart2,
  BarChart3,
  Beer,
  Bot,
  Boxes,
  Brain,
  Building,
  Building2,
  Calculator,
  Calendar,
  CalendarClock,
  ChefHat,
  CircleDollarSign,
  ClipboardList,
  Clock,
  Coffee,
  Cookie,
  CreditCard,
  DollarSign,
  Factory,
  FileSearch,
  FileSpreadsheet,
  FileText,
  Gauge,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  Heart,
  HeartPulse,
  Layers,
  LayoutDashboard,
  LineChart,
  Lock,
  MessageSquare,
  Monitor,
  Network,
  Package,
  PartyPopper,
  PieChart,
  Pill,
  Pizza,
  QrCode,
  Receipt,
  Salad,
  Sandwich,
  ScanLine,
  Settings,
  Shield,
  Ship,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Soup,
  Store,
  Ticket,
  TrendingUp,
  Trees,
  Truck,
  UserCheck,
  UserCog,
  Users,
  UsersRound,
  Utensils,
  UtensilsCrossed,
  Wallet,
  Warehouse,
  Wheat,
  Wrench,
  Zap,
} from "lucide-react";

export type MenuItem = {
  name: string;
  icon: LucideIcon;
  href: string;
  badge?: string;
};

export type MenuGroup = {
  id: string;
  title: string;
  icon: LucideIcon;
  href: string;
  items: MenuItem[];
};

const PRODUCTS_HUB = "/produtos";
const RETAIL_PAGE = "/produtos/retail";

export const productGroups: MenuGroup[] = [
  {
    id: "frente-de-loja",
    title: "Frente de loja",
    icon: Store,
    href: RETAIL_PAGE,
    items: [
      { name: "PDV", icon: Monitor, href: RETAIL_PAGE },
      { name: "SmartPOS", icon: Smartphone, href: RETAIL_PAGE, badge: "Novo" },
      { name: "Autoatendimento", icon: ScanLine, href: RETAIL_PAGE },
      { name: "Honest Market", icon: ShoppingBag, href: RETAIL_PAGE },
      { name: "Cardápio digital", icon: QrCode, href: RETAIL_PAGE },
      { name: "Delivery", icon: Truck, href: RETAIL_PAGE, badge: "Novo" },
      { name: "Cashless", icon: CreditCard, href: RETAIL_PAGE },
      { name: "Ficha/QRCode", icon: QrCode, href: RETAIL_PAGE },
    ],
  },
  {
    id: "tecfood",
    title: "TecFood",
    icon: Utensils,
    href: PRODUCTS_HUB,
    items: [
      { name: "Planejamento de cardápios", icon: ClipboardList, href: PRODUCTS_HUB, badge: "Novo" },
      { name: "Gestão de custos", icon: DollarSign, href: PRODUCTS_HUB, badge: "Novo" },
      { name: "Produção", icon: ChefHat, href: PRODUCTS_HUB },
      { name: "Estoque operacional", icon: Warehouse, href: PRODUCTS_HUB },
      { name: "Controle de refeições", icon: Utensils, href: PRODUCTS_HUB },
      { name: "Gestão nutricional", icon: Salad, href: PRODUCTS_HUB },
      { name: "Contratos", icon: FileText, href: PRODUCTS_HUB },
      { name: "Operação de cozinhas", icon: Soup, href: PRODUCTS_HUB },
    ],
  },
  {
    id: "erp-backoffice",
    title: "ERP Backoffice",
    icon: Building2,
    href: PRODUCTS_HUB,
    items: [
      { name: "Financeiro", icon: DollarSign, href: PRODUCTS_HUB },
      { name: "Fiscal", icon: Receipt, href: PRODUCTS_HUB },
      { name: "Contabilidade", icon: Calculator, href: PRODUCTS_HUB },
      { name: "Compras", icon: ShoppingCart, href: PRODUCTS_HUB },
      { name: "Estoque", icon: Boxes, href: PRODUCTS_HUB },
      { name: "Produção", icon: Factory, href: PRODUCTS_HUB },
      { name: "Orçamento", icon: FileSpreadsheet, href: PRODUCTS_HUB },
      { name: "Controladoria", icon: BarChart3, href: PRODUCTS_HUB },
      { name: "DRE/Fluxo de caixa", icon: LineChart, href: PRODUCTS_HUB },
    ],
  },
  {
    id: "pessoas-rh",
    title: "Pessoas e RH",
    icon: Users,
    href: PRODUCTS_HUB,
    items: [
      { name: "RH", icon: UserCog, href: PRODUCTS_HUB },
      { name: "Folha", icon: Wallet, href: PRODUCTS_HUB },
      { name: "Ponto", icon: Clock, href: PRODUCTS_HUB },
      { name: "Gestão de times", icon: UsersRound, href: PRODUCTS_HUB },
      { name: "Escala de trabalho", icon: CalendarClock, href: PRODUCTS_HUB },
    ],
  },
  {
    id: "supply-compras",
    title: "Supply e compras",
    icon: Package,
    href: PRODUCTS_HUB,
    items: [
      { name: "Portal de compras", icon: ShoppingBag, href: PRODUCTS_HUB },
      { name: "Cotações", icon: FileSearch, href: PRODUCTS_HUB },
      { name: "E-procurement", icon: Globe, href: PRODUCTS_HUB },
      { name: "Gestão de fornecedores", icon: Building, href: PRODUCTS_HUB },
      { name: "Inteligência de compras", icon: Brain, href: PRODUCTS_HUB, badge: "Novo" },
    ],
  },
  {
    id: "crm",
    title: "CRM",
    icon: Heart,
    href: PRODUCTS_HUB,
    items: [
      { name: "Jornada do cliente", icon: UserCheck, href: PRODUCTS_HUB },
      { name: "Fidelidade", icon: Award, href: PRODUCTS_HUB },
      { name: "Cashback", icon: CircleDollarSign, href: PRODUCTS_HUB },
      { name: "Inteligência de consumo", icon: BarChart2, href: PRODUCTS_HUB },
      { name: "Cupom de desconto", icon: Ticket, href: PRODUCTS_HUB },
      { name: "Cartão presente", icon: Gift, href: PRODUCTS_HUB },
    ],
  },
  {
    id: "ia",
    title: "IA",
    icon: Brain,
    href: PRODUCTS_HUB,
    items: [
      { name: "Agentes de IA", icon: Bot, href: PRODUCTS_HUB, badge: "Novo" },
      { name: "Automação operacional", icon: Zap, href: PRODUCTS_HUB },
      { name: "IA para compras", icon: Sparkles, href: PRODUCTS_HUB, badge: "Novo" },
      { name: "IA para gestão financeira", icon: TrendingUp, href: PRODUCTS_HUB },
      { name: "IA para atendimento", icon: MessageSquare, href: PRODUCTS_HUB, badge: "Novo" },
    ],
  },
  {
    id: "gestao-corporativa",
    title: "Gestão corporativa",
    icon: LayoutDashboard,
    href: PRODUCTS_HUB,
    items: [
      { name: "Multiunidades", icon: Layers, href: PRODUCTS_HUB },
      { name: "Franquias", icon: Network, href: PRODUCTS_HUB },
      { name: "Centralização administrativa", icon: Settings, href: PRODUCTS_HUB },
      { name: "Indicadores gerenciais", icon: Gauge, href: PRODUCTS_HUB },
      { name: "BI e Analytics", icon: PieChart, href: PRODUCTS_HUB, badge: "Novo" },
    ],
  },
];

export const segmentGroups: MenuGroup[] = [
  {
    id: "varejo-corporativo",
    title: "Varejo Corporativo",
    icon: Building,
    href: PRODUCTS_HUB,
    items: [
      { name: "Restaurantes corporativos", icon: Building2, href: PRODUCTS_HUB },
      { name: "Cozinhas industriais", icon: Factory, href: PRODUCTS_HUB },
      { name: "Refeições transportadas", icon: Truck, href: PRODUCTS_HUB },
      { name: "Merenda escolar", icon: GraduationCap, href: PRODUCTS_HUB },
      { name: "Alimentação hospitalar", icon: HeartPulse, href: PRODUCTS_HUB },
      { name: "Eventos", icon: Calendar, href: PRODUCTS_HUB },
      { name: "Catering", icon: PartyPopper, href: PRODUCTS_HUB },
      { name: "Offshore", icon: Ship, href: PRODUCTS_HUB },
    ],
  },
  {
    id: "food-service",
    title: "Food Service",
    icon: ShoppingCart,
    href: PRODUCTS_HUB,
    items: [
      { name: "Restaurantes", icon: Utensils, href: PRODUCTS_HUB },
      { name: "Bares", icon: Beer, href: PRODUCTS_HUB },
      { name: "Hamburguerias", icon: Sandwich, href: PRODUCTS_HUB },
      { name: "Pizzarias", icon: Pizza, href: PRODUCTS_HUB },
      { name: "Cafeterias", icon: Coffee, href: PRODUCTS_HUB },
      { name: "Confeitarias", icon: Cookie, href: PRODUCTS_HUB },
      { name: "Self-service", icon: Salad, href: PRODUCTS_HUB },
      { name: "Rodízios", icon: UtensilsCrossed, href: PRODUCTS_HUB },
      { name: "Fast food", icon: Sandwich, href: PRODUCTS_HUB },
      { name: "Dark kitchens", icon: ChefHat, href: PRODUCTS_HUB },
    ],
  },
  {
    id: "industrias",
    title: "Indústrias",
    icon: Factory,
    href: PRODUCTS_HUB,
    items: [
      { name: "Alimentos", icon: Wheat, href: PRODUCTS_HUB },
      { name: "Cosméticos", icon: Sparkles, href: PRODUCTS_HUB },
      { name: "Nutracêuticos", icon: Pill, href: PRODUCTS_HUB },
      { name: "Distribuidores", icon: Truck, href: PRODUCTS_HUB },
    ],
  },
  {
    id: "servicos-terceirizados",
    title: "Serviços terceirizados",
    icon: Wrench,
    href: PRODUCTS_HUB,
    items: [
      { name: "Facilities", icon: Building2, href: PRODUCTS_HUB },
      { name: "Terceirização de MDO", icon: Users, href: PRODUCTS_HUB },
      { name: "Limpeza", icon: Sparkles, href: PRODUCTS_HUB },
      { name: "Portaria", icon: Lock, href: PRODUCTS_HUB },
      { name: "Segurança", icon: Shield, href: PRODUCTS_HUB },
      { name: "Conservação", icon: Hammer, href: PRODUCTS_HUB },
      { name: "Jardinagem", icon: Trees, href: PRODUCTS_HUB },
    ],
  },
];
